### ISSUE TITLE
CI bot performs redundant actions that pollute commit history

### ISSUE THREAD

**Issue by egasimus** [okp4/docs#286]
<table>

<tr>

<td>

One step forward...

![Screenshot from 2023-08-05 15-20-48](https://github.com/okp4/docs/assets/1656054/8739fd23-7569-4b96-ab46-77ec1f908dea)

</td>

<td>

...one step back.

![Screenshot from 2023-08-05 15-20-52](https://github.com/okp4/docs/assets/1656054/b28a9d44-68fc-42b8-825b-e20de15f3c78)

</td>

</table>

There are a lot of commits like that, which are prone to induce unnecessary merge conflicts/rebases (incl. on PR #276).

**Comment by ccamel** [comment]
@egasimus Yes that's true. Our bot is being a bit overzealous in markdown autocorrection. I believe that, just like the linter excludes all generated documentation from evaluation, it should do the same for autocorrection to leave those files untouched.
