### ISSUE TITLE
Whitepaper - Firefox font bug

### ISSUE THREAD

**Issue by ccamel** [okp4/docs#338]
The Norse font appears too bold when we use the Firefox navigator. 

Firefox :x: 

![image.png](https://images.zenhubusercontent.com/616e76157d9dbb44e290ed55/a1ad1840-6935-476d-a78e-4a8e448608ab)

Safari :white_check_mark: 
 
![image.png](https://images.zenhubusercontent.com/616e76157d9dbb44e290ed55/66fac568-aa84-475f-8574-be61b3f9a8fd)

**Comment by JulienMassonnat** [comment]
The problem comes from Firefox and its font rendering. There is a lot of issues about it. I found a solution by adding a font-weight to the h1. 
I can't check on Safari, but it doesn't affect the font on Chrome whereas there is a change on Firefox. I submit a PR.

**Comment by JulienMassonnat** [comment]
Sorry i commited directly on main branch...
https://github.com/okp4/docs/commit/192647ab7e2c15b8adc71079f5f143b439fce1aa
![Sans titre](https://github.com/okp4/docs/assets/63841183/4d3cab03-a1c8-489f-aa3c-33e2c546e569)

**Comment by MdechampG** [comment]
Thx @JulienMassonnat 
It's still not exactly the same as it is on Safari but it's much better !

**Comment by ccamel** [comment]
@MdechampG can we close this one?

**Comment by MdechampG** [comment]
Yes !
